routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function() {
    Route::resource('company', CompanyController::class)->middleware('checkUser');;
    Route::resource('employee', EmployeeController::class)->middleware('checkUser');
    Route::get('/user', function () {
        return view('usernotadmin');
    });
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/CompanyCreate.blade.php
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>

<body>

    <div class="container">
        <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Create New Company</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('company.index') }}"> Back</a>
                </div>
            </div>
        </div>

        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <form action="{{ route('company.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Name:</strong>
                        <input type="text" name="name" class="form-control" placeholder="Input Company Name">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Email:</strong>
                        <input type="email" name="email" class="form-control" placeholder="Input Company Email">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Logo:</strong>
                        <input type="file" name="logo" class="form-control" placeholder="Input Company Logo">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Website:</strong>
                        <input type="text" name="website" class="form-control" placeholder="Input Company Website">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Save Company</button>
                </div>
            </div>

        </form>
    </div>

</body>

</html>

resources/views/CompanyEdit.blade.php
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>

<body>

    <div class="container">
        <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Edit Company</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('company.index') }}"> Back</a>
                </div>
            </div>
        </div>

        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <form action="{{ route('company.update',$company->id) }}" method="POST">
            @csrf
            @method('PUT')

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Name:</strong>
                        <input type="text" name="name" value="{{ $company->name }}" class="form-control" placeholder="Input Company Name">
                    </div>
                    <div class="form-group">
                        <strong>Email:</strong>
                        <input type="text" name="email" value="{{ $company->email }}" class="form-control" placeholder="Input Company Email">
                    </div>
                    <div class="form-group">
                        <strong>Logo:</strong>
                        <input type="file" name="logo" value="{{ $company->logo }}" class="form-control" placeholder="Input Company Logo">
                    </div>
                    <div class="form-group">
                        <strong>Website:</strong>
                        <input type="text" name="website" value="{{ $company->website }}" class="form-control" placeholder="Input Company Website">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Update Company</button>
                </div>
            </div>

        </form>

    </div>
</body>

</html>

resources/views/CompanyIndex.blade.php
@extends('template')

@section('content')
@if ($message = Session::get('success'))
<div class="alert alert-success">
	<p>{{ $message }}</p>
</div>
@endif
<div class="modal fade" id="modal-default">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Edit Company</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form id="company_data" method="POST" enctype="multipart/form-data">
					@csrf
					@method('PUT')

					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12">
							<div class="form-group">
								<strong>Name:</strong>
								<input type="text" name="name" class="form-control" id="name" placeholder="Input Company Name">
								<input type="hidden" name="id" id="id">
							</div>
							<div class="form-group">
								<strong>Email:</strong>
								<input type="text" name="email" class="form-control" id="email" placeholder="Input Company Email">
							</div>
							<div class="form-group">
								<strong>Logo: <small id="logo_view">d</small></strong>
								<input type="file" name="logo" class="form-control" id="logo" placeholder="Input Company Logo">
								<!-- <input type="hidden" name="logo_before" class="form-control" id="logo_before"> -->
							</div>
							<div class="form-group">
								<strong>Website:</strong>
								<input type="text" name="website" class="form-control" id="web_address" placeholder="Input Company Name">
							</div>
						</div>
					</div>
					<div class="modal-footer justify-content-between">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="submit" id="btn_update" class="btn btn-primary">Update Company</button>
					</div>
				</form>
			</div>

		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<div class="card">
	<div class="card-header">
		<div class="float-left">
			<h2>Data Companies</h2>
		</div>
		<div class="float-right">
			<a class="btn btn-success" href="{{ route('company.create') }}"> Add Company</a>

		</div>
	</div>
	<!-- /.card-header -->

	<table class="table table-bordered">
		<tr>
			<th width="20px" class="text-center">No</th>
			<th>Name</th>
			<th>Email</th>
			<th>Logo</th>
			<th>Website</th>
			<th width="280px" class="text-center">Action</th>
		</tr>
		@foreach ($companies as $company)
		<tr>
			<td class="text-center">{{ ++$i }}</td>
			<td>{{ $company->name }}</td>
			<td>{{ $company->email }}</td>
			<td><a target="_blank" href="{{Storage::url($company->logo)}}">See Logo</a></td>
			<td><a target="_blank" href='//{{ $company->website }}'> {{ $company->website }} </a></td>
			<td class="text-center">
				<form action="{{ route('company.destroy',$company->id) }}" method="POST">
					<a class="btn btn-primary btn-sm btn_edit" data-id="{{ $company->id }}" data-toggle="modal" data-target="#modal-default">Edit</a>
					@csrf
					@method('DELETE')

					<button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are You Sure To Delete This Data ?')">Delete</button>
				</form>
			</td>
		</tr>
		@endforeach
	</table>

	{!! $companies->links() !!}
</div>
<!-- /.card-body -->
</div>
<script>
	$(document).ready(function() {
		$(".btn_edit").click(function() {
			var id = $(this).data('id');
			$.ajax({
				url: 'company/' + id + '/edit/',
				type: 'get',
				dataType: 'json',
				success: function(data) {
					$("#web_address").val(data.data.website);
					$("#name").val(data.data.name);
					$("#email").val(data.data.email);
					$("#logo_before").val(data.data.logo);
					$("#logo_view").html(data.data.logo);
					$("#id").val(data.data.id);
					$("#logo").val(data.data.logo);
				}
			});
		});

		$('#company_data').on('submit', function(event) {
			event.preventDefault();
			var id = $("#id").val();
			var form_data = new FormData($("#company_data")[0]);
			$.ajax({
				url: "{{ route('company.update',1) }}",
				method: "POST",
				data: form_data,
				dataType: "json",
				processData: false,
				contentType: false,
				success: function(data) {
					if(data.success)
					{
						alert('Company Successfully Updated');
						location.reload();
					}else{
						alert('Please Check Your data, Name is required & logo must image file');
					}
				}
			})
		});
	});
</script>

@endsection

resources/views/EmployeeCreate.blade.php
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>

<body>

    <div class="container">
        <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Create New Employee</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('employee.index') }}"> Back</a>
                </div>
            </div>
        </div>

        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <form action="{{ route('employee.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>First Name:</strong>
                        <input type="text" name="firstname" class="form-control" placeholder="Input employee First Name">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Last Name:</strong>
                        <input type="text" name="lastname" class="form-control" placeholder="Input employee Last Name">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Company:</strong>
                        <select name="company" class="form-control">
                            <option value="">-- Choose Company -- </option>>
                            @foreach ($companies as $company)
                            <option value="{{ $company->id }}">{{ $company->name }} </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Email:</strong>
                        <input type="text" name="email" class="form-control" placeholder="Input employee Email">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Phone:</strong>
                        <input type="text" name="phone" class="form-control" placeholder="Input employee Phone">
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Save Employee</button>
                </div>
            </div>

        </form>
    </div>

</body>

</html>

resources/views/EmployeeIndex.blade.php
@extends('template')

@section('content')
@if ($message = Session::get('success'))
<div class="alert alert-success">
	<p>{{ $message }}</p>
</div>
@endif
<div class="modal fade" id="modal-default2">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Data Company</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form id="company_data">
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12">
							<div class="form-group">
								<strong>Name:</strong>
								<input type="text" readonly name="name" class="form-control" id="company_name" placeholder="Input Company Name">
							</div>
							<div class="form-group">
								<strong>Email:</strong>
								<input type="text" readonly name="email" class="form-control" id="company_email" placeholder="Input Company Email">
							</div>
							<div class="form-group">
								<strong>Logo: <small id="logo">d</small></strong>
							</div>
							<div class="form-group">
								<strong>Website:</strong>
								<input type="text" readonly name="website" class="form-control" id="company_website" placeholder="Input Company Name">
							</div>
						</div>
					</div>
					<div class="modal-footer justify-content-between">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
				</form>
			</div>

		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>

<div class="modal fade" id="modal-default">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Edit Employee</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form id="employee_data" method="POST" enctype="multipart/form-data">
					@csrf
					@method('PUT')

					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12">
							<div class="form-group">
								<strong>First Name:</strong>
								<input type="text" name="firstname" class="form-control" id="firstname" placeholder="Input Employee First Name">
								<input type="hidden" name="id" id="id">
							</div>
							<div class="form-group">
								<strong>Last Name:</strong>
								<input type="text" name="lastname" class="form-control" id="lastname" placeholder="Input Employee Last Name">
							</div>
							<div class="form-group">
								<strong>Email:</strong>
								<input type="text" name="email" class="form-control" id="email" placeholder="Input Employee Email">
							</div>
							<div class="form-group">
								<strong>Company:</strong>
								<select name="company" id="company" class="form-control">
									@foreach ($companies as $company)
									<option value="{{ $company->id }}">{{ $company->name }} </option>
									@endforeach
								</select>
							</div>
							<div class="form-group">
								<strong>Phone:</strong>
								<input type="text" name="phone" class="form-control" id="phone" placeholder="Input Employee Phone">
							</div>
						</div>
					</div>
					<div class="modal-footer justify-content-between">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="submit" id="btn_update" class="btn btn-primary">Update Company</button>
					</div>
				</form>
			</div>

		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<div class="card">
	<div class="card-header">
		<div class="float-left">
			<h2>Data Employees </h2>
		</div>
		<div class="float-right">
			<a class="btn btn-success" href="{{ route('employee.create') }}"> Add Employee</a>
		</div>
	</div>
	<!-- /.card-header -->

	<table class="table table-bordered">
		<tr>
			<th width="20px" class="text-center">No</th>
			<th>Full Name</th>
			<th>Email</th>
			<th>Company</th>
			<th>Phone</th>
			<th width="280px" class="text-center">Action</th>
		</tr>
		@foreach ($employees as $employee)
		<tr>
			<td class="text-center">{{ ++$i }}</td>
			<td>{{ $employee->firstname }} {{ $employee->lastname }}</td>
			<td>{{ $employee->email }}</td>
			<td><a class="btn btn-primary btn-sm btn_company" data-id="{{ $employee->companyid }}" data-toggle="modal" data-target="#modal-default2">{{ $employee->companyname }}</a></td>
			<td>{{ $employee->phone }}</td>
			<td class="text-center">
				<form action="{{ route('employee.destroy',$employee->id) }}" method="POST">
					<a class="btn btn-primary btn-sm btn_edit" data-id="{{ $employee->id }}" data-toggle="modal" data-target="#modal-default">Edit</a>
					@csrf
					@method('DELETE')

					<button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are You Sure To Delete This Data ?')">Delete</button>
				</form>
			</td>
		</tr>
		@endforeach
	</table>

</div>
<!-- /.card-body -->
</div>

<script>
	$(document).ready(function() {
		$(".btn_edit").click(function() {
			var id = $(this).data('id');
			$.ajax({
				url: 'employee/' + id + '/edit/',
				type: 'get',
				dataType: 'json',
				success: function(data) {
					$('#company').append($('<option>', {
						value: data.data.companyid,
						text: data.data.companyname,
						selected: true
					}));

					$("#firstname").val(data.data.firstname);
					$("#lastname").val(data.data.lastname);
					$("#email").val(data.data.email);
					$("#phone").val(data.data.phone);
					$("#id").val(data.data.id);
				}
			});
		});

		$(".btn_company").click(function() {
			var id = $(this).data('id');
			$.ajax({
				url: 'company/' + id + '/edit/',
				type: 'get',
				dataType: 'json',
				success: function(data) {
					$("#company_website").val(data.data.website);
					$("#company_name").val(data.data.name);
					$("#company_email").val(data.data.email);
					$("#logo").html(data.data.logo);
				}
			});
		});

		$('#employee_data').on('submit', function(event) {
			event.preventDefault();
			var id = $("#id").val();
			var form_data = new FormData($("#employee_data")[0]);
			$.ajax({
				url: "{{ route('employee.update',1) }}",
				method: "POST",
				data: form_data,
				dataType: "json",
				processData: false,
				contentType: false,
				success: function(data) {
					if (data.success) {
						alert('Employee Successfully Updated');
						location.reload();
					} else {
						alert('Please Check Your data, First Name & Last Name is Required');
					}
				}
			})
		});
	});
</script>
@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/usernotadmin.blade.php
This is Not Admin User Logged In Page, only authenticated user can login here
<form method="POST" action="{{ route('logout') }}">
    @csrf

    <x-dropdown-link :href="route('logout')" onclick="event.preventDefault();
                                                this.closest('form').submit();">
        {{ __('Log Out') }}
    </x-dropdown-link>
</form>